title: Epoiisa
description: Gaming tools, mechanics, builds and guides by Epoiisa.
url: "https://epoiisa.github.io"
baseurl: ""
remote_theme: epoiisa/unfettered@main
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
redirect_from:
  json: false
exclude:
  - _preview
  - preview.command
  - .preview
  - .bundle
